config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'user/index'
  get 'lesson/index'


  get '/:week' => 'lessons#index', as: :week_of_lessons

  resources :users
  resources :lessons
  resources :documents

  root 'lessons#index'

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :lesson

  has_attached_file :file
  validates_attachment_file_name :file, matches: [/zip\Z/,/doc\Z/,/png\Z/, /jpe?g\Z/, /txt\Z/]

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :lesson_marks
  has_many :users, through: :lesson_marks
  has_many :documents, dependent: :destroy
  accepts_nested_attributes_for :documents
  
  validates :group_id, :date, presence: true
  LESSON_GROUP = { I18n.t(:middle_group) =>  1,  I18n.t(:senior_group) => 2 }
end

app/models/lesson_mark.rb
class LessonMark < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :lesson_marks
  has_many :lessons, through: :lesson_marks
  validates :group_id, :name, presence: true

  def mark_for_lesson(lesson)
    lesson_marks.where(lesson: lesson).first.try(:mark_for_lesson)
  end

  def mark_for_homework(lesson)
    lesson_marks.where(lesson: lesson).first.try(:mark_for_homework)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << [:name, :group_id]
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

  def destroy
    @document = Document.where(id: params[:id]).first
    if @document.present?
      @document.destroy
    else
      flash[:error] = t(:error_delete)
    end
    redirect_to :back
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def index
    @user = current_user
    @week = week_params[:week].to_i || 0
    start_day = (Time.now + @week.weeks).at_beginning_of_week
    @week_days = (0..4).map { |day_num| (start_day + day_num.days).to_date }
    @lessons_by_day = Lesson.where(date: start_day..start_day.end_of_week)
                                         .group_by{|lesson| lesson.date.to_date}
  end

  def show
    @user = current_user
    @lesson = Lesson.where(id: params[:id]).first
    return redirect_to(lessons_path, flash[:error] = t(:error_show)) unless @lesson
    @users = User.where(group_id: @lesson.group_id).includes(:lesson_marks)
  end

  def new
    @lesson = Lesson.new
    @lesson.documents.build
  end

  def create
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      create_document(@lesson)
    else
      flash[:error] = t(:error_create)
    end
    redirect_to lessons_path
  end

  def update
    @lesson = Lesson.where(id: params[:id]).first
    flash[:error] = t(:error_update) unless @lesson.update_attributes(lesson_params)
    Lesson.transaction do
      lessons_marks_params[:users].each do |lesson_mark_params|
        lesson_user = @lesson.lesson_marks.find_by_user_id(lesson_mark_params[:user_id])
        if lesson_user.present?
          lesson_user.update_attributes(lesson_mark_params)
        else
          @lesson.lesson_marks.create(lesson_mark_params)
        end
      end
    end
    if @lesson.update_attributes(lesson_params)
      create_document(@lesson)
    else
      flash[:error] = t(:error_update)
    end
    return redirect_to :back
  end

  def create_document(lesson)
    docs = params[:documents]
    if docs.present?
      if docs.is_a? Array
        docs.each { |doc| lesson.documents.create file: doc }
      else
        lesson.documents.create file: docs
      end
    end
  end

  def destroy_all_documents
    @lesson = Lesson.where(id: params[:id]).first
    if @lesson.documents.present
      @lesson.documents.each do |del_doc|
        del_doc.destroy
      end
      @lesson.save
    else
      flash[:error] = t(:error_delete)
    end
    redirect_to :back

  end

  private

  def lesson_params
    params.require(:lesson).permit(:hometask, :date, :group_id, documents_attributes: [:id, :name, :file] )
  end

  def lessons_marks_params
    params.permit(users: [:user_id, :mark_for_lesson, :mark_for_homework])
  end

  def week_params
    params.permit(:week)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/lesson_helper.rb
module LessonHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.slim
doctype html

html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= t(:electronic_diary)
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    .navbar.navbar-default role="navigation"
      .container
        .navbar-header
          - if user_signed_in?
            button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
              span.sr-only Toggle navigation
              span.icon-bar
              span.icon-bar
              span.icon-bar
          = link_to t(:electronic_diary), root_path, class: 'navbar-brand'
        .navbar-collapse.collapse
          ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              li
                p.navbar-text
                  = current_user.name
                  |    (
                  = link_to t(:logout), destroy_user_session_path, method: :delete
                  |)

    .container-fluid
      .row
        .col-md-12
          = yield

app/views/lessons/_show.html.slim
= bootstrap_form_for @lesson, :html => { :multipart => true } do |f|
  table.table.table-bordered.show_l
    tr
      th.text-center
        = I18n.l(@lesson.date, format: :short_date)
        br
        = I18n.l(@lesson.date, format: :short_time)
      th.text-center = t(:mark_for_lesson)
      th.text-center = t(:mark_for_homework)
    - if @user.admin?
      - @users.each do |u|
        tr.center
          td = u.name
          = hidden_field_tag 'users[][user_id]', u.id
          td = number_field_tag 'users[][mark_for_lesson]', u.mark_for_lesson(@lesson), in: 0..5
          td = number_field_tag 'users[][mark_for_homework]', u.mark_for_homework(@lesson), in: 0..5
      tr
        td colspan="3" = f.text_area(:hometask, label: t(:homework), placeholder: t(:write_hometask_or_comment), rows: 7)
      tr
        td colspan="3"
          ul
            - @lesson.documents.each do |doc|
              li
                = link_to doc.file_file_name, doc.file.url
                |  /
                = link_to t(:delete), document_path(doc), method: :delete, data: { confirm: "Are you sure?" }, class: "link_delete"
      tr
        td colspan="3" = file_field_tag 'documents[]', type: :file, multiple: true
      tr
        td colspan = "3" = f.submit t(:save), class: 'btn btn-primary'
    - else
      tr.center
        td  = @user.name
        td = @user.mark_for_lesson(@lesson)
        td = @user.mark_for_homework(@lesson)
      tr
        td.center = t(:hometask_or_comments)
        td colspan="2" = @lesson.hometask
      tr
        td colspan="3"
          ul
            - @lesson.documents.each do |doc|
              li
                = link_to doc.file_file_name, doc.file.url
    tr
      td colspan = "3" = link_to t(:cancel), :back, class: 'btn btn-default'

app/views/lessons/index.html.slim
.row.center
  - if flash[:error]
    = flash[:error]

.row
  .col-md-1.center
    = link_to '', week_of_lessons_path(@week - 1), class: "glyphicon glyphicon-arrow-left btn btn-default"
    .add_line
      hr.hr-row
  - @week_days.each do |day|
    .col-md-2
      .panel.panel-default
        .panel-heading
          b
            .text-center
              b= I18n.l(day, format: :short_date_name)
              br
              b= I18n.l(day, format: :short_date)
        - if @lessons_by_day.include? day
          ul.list-group.text-center
            -@lessons_by_day[day].each do |lesson|
              - if @user.admin? || @user.group_id == lesson.group_id
                li.list-group-item
                  = I18n.l(lesson.date, format: :short_time)
                  = link_to "#{Lesson::LESSON_GROUP.key(lesson.group_id)}", lesson_path(lesson.id), remote: true
  .col-md-1.center
    = link_to '', week_of_lessons_path(@week + 1), class: "glyphicon glyphicon-arrow-right btn btn-default"
hr.hr-row
.row.center
  .text-center = link_to t(:add_lesson), new_lesson_path, class: 'btn btn-primary' if @user.admin?
hr.hr-row
.show_lesson

app/views/lessons/new.html.slim
table.table.table-bordered.show_l
  = bootstrap_form_for @lesson do |f|
    tr
      td = f.datetime_field(:date, label: t(:lesson_date), placeholder:  'dd.mm.yy HH:mm')
    tr
      td = f.select(:group_id, Lesson::LESSON_GROUP , { class: "selectpicker" })
    tr
      td = f.text_field(:hometask, label: t(:hometask_or_comments), placeholder: t(:write_hometask_or_comment))
    tr
      td = f.submit t(:create), class: 'btn btn-primary'
  tr
    td = link_to t(:cancel), :back, class: 'btn btn-default'

app/views/lessons/show.js.slim
|$(".show_lesson").replaceWith("#{j render(partial: 'show') }");